blank_issues_enabled: false
contact_links:
  - name: Ask a Question / General Discussion
    url: https://github.com/drew-simmons/skrvm/discussions
    about: Please ask questions, share ideas, and get support in our GitHub Discussions forum.
